[package]
name = "fts_gitignore_clean"
version = "0.1.0"
authors = ["Forrest Smith <forrestthewoods@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
ignore = "0.4.15"
itertools = "0.9.0"
num-format = "0.4.0"
walkdir = "2.3.1"